blueprint:
    name: Dimmer remote and motion sensor combined automation
    description: Control light with a motion sensor and a remote dimmer. To use with IKEA dimmer switches.
    domain: automation
    source_url: https://github.com/dimamedia/ha_blueprints/blob/main/Remote%20dimmer%20and%20motion%20sensor%20combined%20automation.yml
    author: Dima Tsvetkov
    
    input:
        remote_device:
            name: Remote dimmer switch
            selector:
                device:
        motion_sensor:
            name: Motion sensor
            description: Select motion sensor
            selector:
                entity:
                    filter:
                        device_class: motion
                        domain: binary_sensor
        target_light:
            name: Target light
            selector:
                entity:
                    domain: light
        helper_light_lock:
            name: Helper - light lock
            description: Boolean helper to keep light on when turned on manually
            selector:
                entity:
                    domain: input_boolean
        helper_night_time:
            name: Helper - night time
            description: Binary helper for predefined nighttime
            selector:
                entity:
                    domain: binary_sensor
        night_brightness:
            name: Night brightness
            description: Light brightness in night mode
            default: 20
            selector:
                number:
                    min: 0
                    max: 100
                    unit_of_measurement: "%"
        no_motion_time:
            name: No motion time to wait
            description: Set the wait time before turning off the light after no motion is detected (minutes)
            default: 5
            selector:
                number:
                    min: 0
                    max: 60
                    unit_of_measurement: minutes
        no_presence_time:
            name: No presence time
            description: Set the max time for empty presence to turn off manually switched light (minutes)
            default: 60
            selector:
                number:
                    min: 0
                    max: 720
                    unit_of_measurement: minutes
    
mode: restart
    
trigger:
  - device_id: !input remote_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
    id: Turn-on
  - device_id: !input remote_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
    id: Turn-off
  - device_id: !input remote_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_up
    id: Dim-up
  - device_id: !input remote_device
    domain: zha
    platform: device
    type: remote_button_long_release
    subtype: dim_up
    id: Dim-up released
  - device_id: !input remote_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
    id: Dim-down
  - device_id: !input remote_device
    domain: zha
    platform: device
    type: remote_button_long_release
    subtype: dim_down
    id: Dim-down released
  - type: motion
    platform: device
    entity_id: !input motion_sensor
    domain: binary_sensor
    id: Motion start
  - type: no_motion
    platform: device
    entity_id: !input motion_sensor
    domain: binary_sensor
    id: Motion end
    for:
      hours: 0
      minutes: !input no_motion_time 
      seconds: 0
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Turn-on
        sequence:
          - service: light.turn_on
            metadata: {}
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 1
            target:
              entity_id: !input target_light
          - service: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.ylaaula_valo_lukko
      - conditions:
          - condition: trigger
            id:
              - Turn-off
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light
            data:
              transition: 1
          - service: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.ylaaula_valo_lukko
            data: {}
      - conditions:
          - condition: trigger
            id:
              - Dim-up
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  metadata: {}
                  data:
                    transition: 1
                    brightness_step_pct: 5
                  target:
                    entity_id: !input target_light
              until:
                - condition: trigger
                  id:
                    - Dim-up released
      - conditions:
          - condition: trigger
            id:
              - Dim-down
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  metadata: {}
                  data:
                    transition: 1
                    brightness_step_pct: -5
                  target:
                    entity_id: !input target_light
              until:
                - condition: trigger
                  id:
                    - Dim-down released
      - conditions:
          - condition: trigger
            id:
              - Motion start
          - condition: state
            entity_id: !input helper_light_lock
            state: "off"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input helper_night_time
                    state: "on"
                sequence:
                  - service: light.turn_on
                    metadata: {}
                    data:
                      transition: 1
                      brightness_pct: !input night_brightness
                      kelvin: 2000
                    target:
                      entity_id: !input target_light
            default:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 1
                  kelvin: 3000
                  brightness_pct: 100
                target:
                  entity_id: !input target_light
      - conditions:
          - condition: trigger
            id:
              - Motion end
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input helper_light_lock
                    state: "on"
                sequence:
                  - delay:
                      hours: 0
                      minutes: !input no_presence_time
                      seconds: 0
                      milliseconds: 0
                  - service: light.turn_off
                    metadata: {}
                    data:
                      transition: 1
                    target:
                      entity_id: !input target_light
            default:
              - delay:
                  hours: 0
                  minutes: !input no_motion_time
                  seconds: 0
                  milliseconds: 0
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 1
                target:
                  entity_id: !input target_light
