blueprint:
  name: "ROBB Smarrt - (RGB, CCT, Dimmer, Scene) 3-Channel Control"
  description: >
    # Robb smarrt remote controller
    Control up to 3 light groups. Includes Toggle, RGB, CCT, Dimming, and Scene Store/Recall.

    - **3 channel**
      - Assign multiple lights to each channel and toggle channels with 1-3 buttons. So it’s possible to control even all selected channels at the same time.

    - **Power button**
      - Toggles lights on or off.

    - **CCT slide**
      - Controls color temperature from cold to warm.

    - **RGB wheel**
      - Controls light hue 0-360°.
    
    - **Dimmer buttons**
      - Dim or brighten lights in 10% steps with short press.
      - Continuously dim or brighten lights with long press.

    - **Scene buttons**
      - Store current light settings as a scene with long press.
      - Recal stored scene with short press.
      - 1-5 scenes for each group.
      - Button 6 is not working as it doesn’t send any event to zha.

  domain: automation
  input:
    remote:
      name: "Remote Control"
      selector:
        device:
          integration: zha
          filter:
            - manufacturer: "ROBB smarrt"
    light_1:
      name: "Light group 1"
      default: 
      selector:
        target:
          entity:
            domain: light
    light_2:
      name: "Light group 2"
      default: 
      selector:
        target:
          entity:
            domain: light
    light_3:
      name: "Light group 3"
      default: 
      selector:
        target:
          entity:
            domain: light

mode: parallel
max: 10

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "on"
    id: "toggle"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "off"
    id: "toggle"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "move_to_color"
    id: "rgb"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "move_to_color_temp"
    id: "cct"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "step_with_on_off"
    id: "step"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "move_with_on_off"
    id: "hold"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "recall"
    id: "recall"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      command: "store"
    id: "store"

action:
  - variables:
      endpoint: "{{ trigger.event.data.endpoint_id }}"
      # Map targets
      target_map:
        1: !input light_1
        2: !input light_2
        3: !input light_3
      
      target_data: "{{ target_map.get(endpoint) }}"
      # Extract entity_id for logic (takes the first entity from the list for calculations)
      first_entity: >
        {% if target_data.entity_id is defined %}
          {% if target_data.entity_id is string %}
            {{ target_data.entity_id }}
          {% else %}
            {{ target_data.entity_id[0] }}
          {% endif %}
        {% else %}
          none
        {% endif %}

  # Stop if no lights are assigned
  - condition: template
    value_template: "{{ first_entity != 'none' }}"

  - choose:
      # --- TOGGLE ---
      - conditions:
          - condition: trigger
            id: "toggle"
        sequence:
          - action: light.toggle
            target: "{{ target_data }}"

      # --- SCENE RECALL ---
      - conditions:
          - condition: trigger
            id: "recall"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: "scene.{{ first_entity.split('.')[1] }}_{{ trigger.event.data.params.scene_id }}"

      # --- SCENE STORE ---
      - conditions:
          - condition: trigger
            id: "store"
        sequence:
          - action: scene.create
            data:
              scene_id: "{{ first_entity.split('.')[1] }}_{{ trigger.event.data.params.scene_id }}"
              snapshot_entities: "{{ first_entity }}"

      # --- RGB (Only if ON) ---
      - conditions:
          - condition: trigger
            id: "rgb"
          - condition: template
            value_template: "{{ is_state(first_entity, 'on') }}"
        sequence:
          - action: light.turn_on
            target: "{{ target_data }}"
            data:
              xy_color:
                - "{{ trigger.event.data.params.color_x / 65535 }}"
                - "{{ trigger.event.data.params.color_y / 65535 }}"
              transition: 0.5

      # --- CCT (Only if ON) ---
      - conditions:
          - condition: trigger
            id: "cct"
          - condition: template
            value_template: "{{ is_state(first_entity, 'on') }}"
        sequence:
          - action: light.turn_on
            target: "{{ target_data }}"
            data:
              color_temp: "{{ trigger.event.data.args[0] }}"
              transition: 0.5

      # --- STEP ---
      - conditions:
          - condition: trigger
            id: "step"
        sequence:
          - action: light.turn_on
            target: "{{ target_data }}"
            data:
              brightness_step_pct: "{{ 13 if trigger.event.data.params.step_mode == 0 else -13 }}"
              transition: 0.3

      # --- HOLD ---
      - conditions:
          - condition: trigger
            id: "hold"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {% set current = state_attr(first_entity, 'brightness') | float(0) %}
                    {% set mode = trigger.event.data.params.move_mode %}
                    {% if mode == 0 %}
                      {{ current < 255 and repeat.index < 20 }}
                    {% else %}
                      {{ current > 26 and repeat.index < 20 }}
                    {% endif %}
              sequence:
                - action: light.turn_on
                  target: "{{ target_data }}"
                  data:
                    brightness_step_pct: "{{ 10 if trigger.event.data.params.move_mode == 0 else -10 }}"
                    transition: 0.5
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        command: "stop_with_on_off"
                        endpoint_id: "{{ endpoint | int }}"
                  timeout: "00:00:00.5"
                  continue_on_timeout: true
                - if:
                    - condition: template
                      value_template: "{{ wait.trigger is not none }}"
                  then:
                    - stop: "Button released"
