blueprint:
  name: "ROBB Smarrt - (RGB, CCT, Dimmer, Scene) 3-Channel Control"
  description: "Control up to 3 lights. Includes Toggle, RGB, CCT, Dimming, and Scene Store/Recall."
  domain: automation
  input:
    remote:
      name: "Remote Control"
      description: "Select the ROBB Smarrt remote device."
      selector:
        device:
          integration: zha
          filter:
            - manufacturer: "ROBB Smarrt"
    light_1:
      name: "Light - Channel 1"
      description: "Light controlled by endpoint 1."
      default: []
      selector:
        entity:
          domain: light
    light_2:
      name: "Light - Channel 2"
      description: "Light controlled by endpoint 2."
      default: []
      selector:
        entity:
          domain: light
    light_3:
      name: "Light - Channel 3"
      description: "Light controlled by endpoint 3."
      default: []
      selector:
        entity:
          domain: light

mode: parallel
max: 10

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      endpoint: "{{ trigger.event.data.endpoint_id }}"
      params: "{{ trigger.event.data.params }}"
      args: "{{ trigger.event.data.args }}"
      
      # Map the target light based on the endpoint ID (1-3)
      target_light: >
        {% if endpoint == 1 %} !input light_1
        {% elif endpoint == 2 %} !input light_2
        {% elif endpoint == 3 %} !input light_3
        {% else %} none
        {% endif %}
      
      entity_name: "{{ target_light.split('.')[1] if target_light is not none and target_light != 'none' }}"
      scene_id_val: "{{ params.scene_id if params.scene_id is defined else 0 }}"
      scene_entity: "scene.{{ entity_name }}_{{ scene_id_val }}"
      scene_slug: "{{ entity_name }}_{{ scene_id_val }}"

  - condition: template
    value_template: "{{ target_light is not none and target_light != 'none' }}"

  - choose:
      # --- TOGGLE ---
      - conditions: "{{ command in ['on', 'off'] }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: "{{ target_light }}"

      # --- SCENE RECALL (Short Press) ---
      - conditions: "{{ command == 'recall' }}"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: "{{ scene_entity }}"

      # --- SCENE STORE (Long Press) ---
      - conditions: "{{ command == 'store' }}"
        sequence:
          - action: scene.create
            data:
              scene_id: "{{ scene_slug }}"
              snapshot_entities:
                - "{{ target_light }}"

      # --- RGB (Only if ON) ---
      - conditions: 
          - "{{ command == 'move_to_color' }}"
          - "{{ is_state(target_light, 'on') }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              xy_color:
                - "{{ params.color_x / 65535 }}"
                - "{{ params.color_y / 65535 }}"
              transition: 0.5

      # --- CCT (Only if ON) ---
      - conditions:
          - "{{ command == 'move_to_color_temp' }}"
          - "{{ is_state(target_light, 'on') }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              color_temp: "{{ args[0] }}"
              transition: 0.5

      # --- BRIGHTNESS STEP ---
      - conditions: "{{ command == 'step_with_on_off' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: "{{ 13 if params.step_mode == 0 else -13 }}"
              transition: 0.3

      # --- DIMMING HOLD ---
      - conditions: "{{ command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {% set current = state_attr(target_light, 'brightness') | float(0) %}
                    {% set mode = params.move_mode %}
                    {% if mode == 0 %}
                      {{ current < 255 and repeat.index < 20 }}
                    {% else %}
                      {{ current > 26 and repeat.index < 20 }}
                    {% endif %}
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: "{{ target_light }}"
                  data:
                    brightness_step_pct: "{{ 10 if params.move_mode == 0 else -10 }}"
                    transition: 0.5
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        command: "stop_with_on_off"
                        endpoint_id: "{{ endpoint | int }}"
                  timeout: "00:00:00.5"
                  continue_on_timeout: true
                - if:
                    - condition: template
                      value_template: "{{ wait.trigger is not none }}"
                  then:
                    - stop: "Released"
